apiVersion: compute.functionmesh.io/v1alpha1
kind: Function
metadata:
  name: function-mesh-example
  namespace: function-mesh
spec:
  image: function-mesh-example:latest # using function image here
  className: org.example.ExclamationFunction
  forwardSourceMessageProperty: true
  maxPendingAsyncRequests: 1000
  replicas: 1
  maxReplicas: 1
  logTopic: persistent://public/default/log-topic
  input:
    topics:
    - persistent://public/default/input-topic
    typeClassName: java.lang.String
  output:
    topic: persistent://public/default/output-topic
    typeClassName: java.lang.String
  pulsar:
    pulsarConfig: "mesh-test-pulsar"
  java:
    extraDependenciesDir: random-dir/
    jar: /pulsar/example-function.jar # the package location in image
    jarLocation: "" # leave empty since we will not download package from Pulsar Packages
  resources:
    requests:
      cpu: "0.1"
      memory: 1G
    limits:
      cpu: "0.2"
      memory: 1.1G
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mesh-test-pulsar
data:
  webServiceURL: pulsar://localhost:8080
  brokerServiceURL: pulsar://localhost:6650