apiVersion: compute.functionmesh.io/v1alpha1
kind: Function
metadata:
  name: function-mesh-example
  namespace: function-mesh
spec:
  className: org.example.ExclamationFunction
  replicas: 1
  maxReplicas: 3
  input:
    topics:
    - persistent://public/default/input-topic
    typeClassName: java.lang.String
  output:
    topic: persistent://public/default/output-topic
    typeClassName: java.lang.String
  pulsar:
    pulsarConfig: "mesh-test-pulsar"
  resources:
    limits:
      cpu: "0.2"
      memory: 0.3G
    requests:
      cpu: "0.1"
      memory: 0.3G
  java:
    extraDependenciesDir: random-dir/
    jar: /pulsar/pulsar-function-1.0-SNAPSHOT.jar # the package location in image
    jarLocation: "" # leave empty since we will not download package from Pulsar Packages
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mesh-test-pulsar
data:
  webServiceURL: pulsar://localhost:8080
  brokerServiceURL: pulsar://localhost:6650
